<a href="https://colab.research.google.com/github/ashwin-77/numpy/blob/main/data_science_numpy_week_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#NUMPY

import numpy as np   #it is known as numerical python

#1.ARRAY:= collection of data with same datatype(homogenous)

#a=np.array([1,2,3.0,4])       #in thi if we give float to one no. the all the o/p will become float
a=np.array([1,2,3,4,"a"])     #in this if we use a string eg. "A" then all the o/p will become string
print(a)

['1' '2' '3' '4' 'a']


In [ ]:
#slicing.. forward slicing , bacward slicing


b=np.array([1,2,3,4,5])
#1,2
print(b[0:2])

#5,4

print(b[-1:-3:-1])
#4,5
print(b[3:])

#2,1
print(b[-4::-1])


[1 2]
[5 4]
[4 5]
[2 1]


In [ ]:
#dimension   := for this we use function "ndim"

a=np.array([1,2,3,4])
#print(a.ndim)      #dimension vector =1
b=np.array(([5,6],[7,8]))
print(b.ndim)        #dimenson vector =2

b.shape              #"shape is used to known how  much rows and  col present ie.to know the shape"

2


(2, 2)

In [ ]:
#create a 2X2 matrix  2,3,4,5

a=np.array(([2,3],[4,5]))
print(a.ndim)
print(a)
print(a.shape)

print(a.size)     #"size is used to get the total  no. of elements"


2
[[2 3]
 [4 5]]
(2, 2)
4


In [ ]:
#create 2X3 matrix and print , size ,shape, dimension

p=np.array(([1,2,3],[4,5,6]))
print(p)
print(p.size)
print(p.shape)
print(p.ndim)

[[1 2 3]
 [4 5 6]]
6
(2, 3)
2


In [ ]:
#create a 4X2 matrix display its size ,shape , dimension

c=np.array(([1,2],[3,4],[5,6],[7,8]))
print(c)
print(c.size)
print(c.shape)
print(c.ndim)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
8
(4, 2)
2


In [ ]:
#create a 4X4 matrix
v=np.array(([1,2,3,4],[5,6,7,8],[2,4,6,8],[1,3,5,7]))
print(v)
print(v.ndim)
print(v.shape)

[[1 2 3 4]
 [5 6 7 8]
 [2 4 6 8]
 [1 3 5 7]]
2
(4, 4)


**19-09-25**

In [ ]:
import numpy as np
#create a 4X4 matrix
v=np.array(([1,2,3,4],[5,6,7,8],[2,4,6,8],[1,3,5,7]))
#print(v.ndim)
#print(v)
#print(v.ndim)
#print(v.shape)

print(v[0])       #to get first row
print(v[:,0])     #to get the first column
print(v[1,1])     #to get the element "6", here first mention its row no., then the col no.
print(v[2,3])     #to get 8
print(v[3,2:])    #to get the value [5,7]
print(v[2:,2:])    #to get 3rd row's [6,8] and from 4th row's [5,7] like [6,8]
                                                                        #[5,7]
print(v[2:,1:3])
print(v[1:3,3])    #to get  [8,8] ie 2nd row lst and 3rd row lst
print(v[1:3,0:3])    #to get 2nd row [5,6,7] and 3rd row [2,4,6]
print(v[0:3,1:])      #to get 1st row [2,3,4] 2nd [6,7,8] 3rd[4,6,8]
print(v[0:,0:])       #to get the all matrix

[1 2 3 4]
[1 5 2 1]
6
8
[5 7]
[[6 8]
 [5 7]]
[[4 6]
 [3 5]]
[8 8]
[[5 6 7]
 [2 4 6]]
[[2 3 4]
 [6 7 8]
 [4 6 8]]
[[1 2 3 4]
 [5 6 7 8]
 [2 4 6 8]
 [1 3 5 7]]


In [ ]:
#zero matrix
z=np.zeros([3,3,3],dtype=int)      #here if we give dtype=int  then it change the matrix to int and dtype= complex it chage
print(z)

[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]


In [ ]:
#ONE Matrix

a=np.ones([3,3],dtype=int)
print(a)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [ ]:
#create two 2X2 matrix

a=np.array([[1,2],[3,4]])
b=np.array([[3,1],[6,7]])
print(a)
print(b)

[[1 2]
 [3 4]]
[[3 1]
 [6 7]]


In [ ]:
#matrix addition
a=np.array([[1,2],[3,4]])
b=np.array([[3,1],[6,7]])
print(a+b)

[[ 4  3]
 [ 9 11]]


In [ ]:
#matrix substraction

a=np.array([[1,2],[3,4]])
b=np.array([[3,1],[6,7]])
print(a-b)

[[-2  1]
 [-3 -3]]


In [ ]:
#matrix multiplication

print(a*b)     #it is not a matrix  mulitiplication
print(a@b)      #for matrix multiplication we use "@" then only we get the correct
print(a.dot(b))   #another matrix multiplication  method

[[ 3  2]
 [18 28]]
[[15 15]
 [33 31]]
[[15 15]
 [33 31]]


In [ ]:
#matrix division

print(a/b)

[[0.33333333 2.        ]
 [0.5        0.57142857]]


In [ ]:
#full matrix    #it is all the elements are same

p=np.full([3,3],5,dtype=int)     #here [3,3] how much we need and 5 is what value is to be given
print(p)

[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [ ]:
#create a 3X4 matrix with value 9 and datatype complex

s=np.full([3,4],9,dtype=complex)
print(s)

[[9.+0.j 9.+0.j 9.+0.j 9.+0.j]
 [9.+0.j 9.+0.j 9.+0.j 9.+0.j]
 [9.+0.j 9.+0.j 9.+0.j 9.+0.j]]


In [ ]:
#identity matrix    # is called when diagonal =1 and it should be square matrix

c=np.identity(3,dtype=int)
print(c)
c=np.eye(3,dtype=int)    #another method for identity matrix
print(c)

[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [ ]:
#create a 4X4 matrix
y=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
print(y)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [ ]:
a=y.reshape(8,2)     #to reshape the matrix but condition is it accept all element ,here it have 16 elements so it can have [4,4],[16,1],[8,2]
print(a)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]]


In [ ]:
#ARANGE


a=np.arange(1,10,2)    #to get range element
print(a)

[1 3 5 7 9]


In [ ]:
#create a 5X2 matrix using arange

z=np.arange(1,11).reshape(5,2)
print(z)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [ ]:
#create a 3X3 matrix with float values
c=np.array([[2.5,3.6,4.7],[1.2,3.5,6.8],[7.1,4.5,8.9]])
print(c)

[[2.5 3.6 4.7]
 [1.2 3.5 6.8]
 [7.1 4.5 8.9]]


In [ ]:
#FLOOR       2.5=2, 3.6=3
w=np.floor(c)
print(w)

[[2. 3. 4.]
 [1. 3. 6.]
 [7. 4. 8.]]


In [ ]:
#celi     here 2.5=3, 3.8=4
d=np.ceil(c)
print(d)

[[3. 4. 5.]
 [2. 4. 7.]
 [8. 5. 9.]]


In [ ]:
#ROUND              #in this case .5 move towards even no. if it is 3.5 then it is 4

r=np.round(c)
print(r)

[[2. 4. 5.]
 [1. 4. 7.]
 [7. 4. 9.]]


In [ ]:
#create 3X3 matrix

a=np.arange(1,10).reshape(3,3)
print(a)

#MAX

print(a.max())    #to find the max element

print(a.max(axis=1)) #in numpy axis=1 is row and axis =0 is column "axis" is used to find the large element in each row or col
print(a.max(axis=0))

#MIN

print(a.min())  #to find the min value
print(a.min(axis=1))   #min value in each row
print(a.min(axis=0))  #min value in each column

[[1 2 3]
 [4 5 6]
 [7 8 9]]
9
[3 6 9]
[7 8 9]
1
[1 4 7]
[1 2 3]


**22-09-25**

In [8]:
#SUM
import numpy as np
p=np.array(([1,2,3],[4,5,6],[7,8,9]))
#print(p)
#print(p.sum())
#print(p.sum(axis=1))     #to find sum of each row
#print(p.sum(axis=0))     #to find sum of each column

#print(np.sqrt(p))            #to get squareroot
#print(np.sin(p))            #to get the sin
#print(np.cos(p))
print(np.tan(p))


[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [2.64575131 2.82842712 3.        ]]


In [10]:
#FLATTEN

import numpy as np
p=np.array(([1,2,3],[4,5,6],[7,8,9]))

print(p.flatten())       #to convert it into one dimensionsal array "vector"

[1 2 3 4 5 6 7 8 9]


In [19]:
#SORT

#create  3X3 matrix

import numpy as np
s=np.array(([3,4,1],[5,3,1],[6,9,8]))
#print(s)
#b=np.sort(s,axis=0)        #METHOD USED FOR SORTING in the column
#b=np.sort(s,axis=1)         #used to sort the row
p#rint(b)

#ARG SORTING

c=np.argsort(s,axis=1)       #sorting on the basis of indexing no. in the o/p we get the matrix with index no.
print(c)

[[2 0 1]
 [2 1 0]
 [0 2 1]]
